---
name: CI Build and Push

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true

jobs:
  build-and-push:
    if: ${{ github.event.label.name == 'CI:TriggerBuild' }}
    runs-on: self-hosted

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app-name }}:latest

  trigger-actions:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{ secrets.DOCKERHUB_USERNAME }}',
              repo: 'zkevm-node',
              workflow_id: 'provision.yml',
              ref: 'main'
            })
